### ISSUE TITLE
PSAT Report additions

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#1591] opened 2018-04-13 17:41 UTC
Make PSAT report more like PHAST report.

Executive Summary
Result Data as the label for both.
Report Graphs
Sankey
Input Data
Facility Info 

Energy Used?? Probably not, but other tabs should be in both.

**Comment by koay9f** [comment] 2018-04-13 21:08
Duplicate of...

**Closed** 2018-04-18 14:32 UTC
Labels: Reports, duplicate, in progress, psat
