### ISSUE TITLE
Weather autobin 2 parameters

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5769] opened 2022-07-06 16:43 UTC
Make it so you can have 2 parameters for auto binning

**Comment by nbintertech** [comment] 2022-07-12 15:04
Holding on this until after release issues are finalized

**Comment by nbintertech** [comment] 2023-12-15 11:52
Closing - after talking with Kristina this is duplicate of more detailed #6375

**Closed by nbintertech** 2023-12-15 11:52 UTC
Labels: Calculator
