### ISSUE TITLE
General Issues with Steam

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#2427] opened 2018-10-09 13:57 UTC

**Comment by vanced** [comment] 2018-10-09 14:02
When switching tabs to the Header tab, Main tab updates but the help and the tab highlighting don't update.

If Header is the first tab that pulls up only the area with the fields is visible. Rest of screen is grey

**Comment by vanced** [comment] 2018-10-09 14:04
![Issue 2427_1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46c187893687c3fbdbbbe87cf51fbcd6395428792c07b7692ac7b671bb4779005d0b47ab100e0d16fcf98c2cf0b73923d85a19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bf834cc9eb3521e2888a4d2c53.png)
![Issue 2427_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46c187893687c3fbdbbbe87cf61fbcd6395428792c07b7692ac7b671bb4779005d0b47ab100e0d16fcf98c2cf0b73923d85a19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bf834cc9eb3520e58d88462c53.png)

**Comment by koay9f** [comment] 2018-10-09 15:04
* I was unable to reproduce that problem on the branch `steam` (David uses Mac, I used Windows)

* When I tried to make a modifcation scneario, the screen went dark like it was pulling up a popup/modal or a tutorial, but nothing ever appeared.  was unable to click on anything in the tool and had to close it.

* When made a new assessment, it defaulted to last page I was on (Assessment) and then when navigated back to system setup it went to Header (last tab I was on)

**Closed** 2018-10-25 17:11 UTC
Labels: needs verification, ssmt
