### ISSUE TITLE
Psychometric Calc using Fan's Air Density

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3744] opened 2020-05-15 14:39 UTC
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/88b57c1b-32bc-4c2c-abbb-77275a296f26)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6676afb5-12e6-4cfd-9519-10d1e923b311)

Add Table like Steam properties

**Comment by koay9f** [comment] 2020-05-15 14:40
may need suite #501

**Comment by nbintertech** [comment] 2020-06-09 20:12
Closing - is duplicate of 3667

**Closed** 2020-06-09 20:13 UTC
Labels: Calculator, duplicate
